version: '3.8'
services:
  postgres-dio:
    image: postgres:16
    container_name: postgres-dio
    environment:
      POSTGRES_DB: dio
      POSTGRES_USER: board
      POSTGRES_PASSWORD: 1board23
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dio-network

  dio-app:
    build: .
    depends_on:
      - postgres-dio
    networks:
      - dio-network

volumes:
  pgdata:

networks:
  dio-network:
    driver: bridge
