
version: '3.8'
services:
  db:
    image: postgres
    container_name: board_postgres
    environment:
      POSTGRES_DB: boarddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - board-network

  app:
    build: .
    container_name: board_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/boarddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    stdin_open: true
    tty: true
    networks:
      - board-network

volumes:
  db_data:

networks:
  board-network:
